### ISSUE TITLE
package.json 支持通过参数传入

### ISSUE THREAD

**Issue by sorrycc** [popomore/father#34]
需求：

totoro-fn 的场景中可能没有 `package.json`，但又需要通过  spm 打包成 standalone 。

**Comment by popomore** [comment]
不是一个包？

**Comment by sorrycc** [comment]
不是包，只打相对文件以及一些固定的全局依赖。

**Comment by popomore** [comment]
不是包 father 应该分析不出来

**Comment by popomore** [comment]
感觉应该还是需要包，不然 main 都解析不出

**Comment by sorrycc** [comment]
这个不需要做了。
